events {}

http {
  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth-service:5001/api/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Request-Id $request_id;
    }

    location /api/jobs/ {
      proxy_pass http://job-service:5002/api/jobs/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Request-Id $request_id;
    }

    location /api/uploads/ {
      proxy_pass http://auth-service:5001/api/uploads/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}